version: "3"
services:
  producer:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - kafka
    networks:
      - app-network
  kafka:
    image: confluentinc/cp-kafka:5.5.0
    ports:
      - "9093:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9091
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_ZOOKEEPER_CONNECT: localhost:2181
    networks:
      - app-network

  zookeeper:
    image: zookeeper:latest
    ports:
      - "2182:2181"
networks:
  app-network:
